# Generated by Django 4.2.7 on 2023-11-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wmenu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="title",
            field=models.CharField(
                help_text='Enter "Main" for the primary menu.', max_length=255
            ),
        ),
    ]
